---
version: '3.8'

services:
  mcp-coordinator:
    build:
      context: .
      dockerfile: docker/coordinator.Dockerfile
    ports:
      - "8002:8002"
    environment:
      - MCP_SERVER_PORT=8002
      - LOG_LEVEL=INFO
      - MOUNT_TOOLS=true
      - MOUNT_REPORTS=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - mcp-network

  mcp-tools:
    build:
      context: .
      dockerfile: docker/tools.Dockerfile
    ports:
      - "8003:8003"
    environment:
      - MCP_SERVER_PORT=8003
      - LOG_LEVEL=INFO
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - mcp-network

  mcp-reports:
    build:
      context: .
      dockerfile: docker/reports.Dockerfile
    ports:
      - "8004:8004"
    environment:
      - MCP_SERVER_PORT=8004
      - LOG_LEVEL=INFO
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8004/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  mcp-data:
    driver: local