[project]
name = "mcp-tools"
version = "1.0.0"
description = "FastMCP Tools Server - Development workflow tools for PR analysis, code review, and automation"
authors = [
    { name = "dlighty", email = "dlighty@example.com" }
]
requires-python = ">=3.11"
dependencies = [
    "fastmcp>=2.10.2",
    "httpx>=0.28.1",
    "psutil>=7.0.0",
]
keywords = ["mcp", "model-context-protocol", "fastmcp", "tools", "pr-analysis", "code-review", "workflow"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12", 
    "Programming Language :: Python :: 3.13",
]

[project.scripts]
mcp-tools = "src.mcp_tools_server:mcp"

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "pytest-asyncio>=0.21.0",
    "pytest-httpx>=0.22.0",
    "black>=23.0.0",
    "ruff>=0.1.0",
    "mypy>=1.0.0",
]
test = [
    "pytest>=7.0.0", 
    "pytest-asyncio>=0.21.0",
    "pytest-httpx>=0.22.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
